import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { Session } from "next-auth";
import { ReactNode } from "react";
import NextAuthProvider from "@/components/NextAuthProvider";
import ReactQuery from "@/components/ReactQuery";
import { AppProvider } from "./context/AppContext";
import AppTheme from "@/components/AppTheme";

const inter = Inter({ subsets: ["latin"] });

interface NextAuthProps {
  children: ReactNode;
  session: Session | null | undefined;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }: NextAuthProps) {
  return (
    <>
      <html lang="en">
        <body className={"h-screen w-screen"}>
          <NextAuthProvider session={session}>
            <ReactQuery>
              {""}
              <AppProvider children={children}>
                
              </AppProvider>
            </ReactQuery>
          </NextAuthProvider>
        </body>
      </html>
    </>
  );
}
